spring:
  application:
    name: sample
  cloud:
    aws:
      region:
        static: ap-northeast-2

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  health:
    probes:
      enabled: true
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

sample:
  id: ${id:test}
  password: ${password:test}

custom:
  token: ${token_value:U2FtcGxlIERldk9wcyB0b2tlbiB2YWx1ZXMK}
